CREATE TABLE `admins` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`available` integer DEFAULT 0 NOT NULL,
	`clerk_user_id` text,
	`name_first` text,
	`name_last` text,
	`name_display` text NOT NULL,
	`email` text NOT NULL,
	`phone` text,
	`phone_mobile` text,
	`timezone` text DEFAULT 'America/New_York'
);
--> statement-breakpoint
CREATE UNIQUE INDEX `admins_clerk_user_id_unique` ON `admins` (`clerk_user_id`);--> statement-breakpoint
CREATE TABLE `advisors` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 0 NOT NULL,
	`available` integer DEFAULT 0 NOT NULL,
	`clerk_user_id` text,
	`name_first` text,
	`name_last` text,
	`name_display` text NOT NULL,
	`subtitle` text,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT 0 NOT NULL,
	`phone` text,
	`phone_verified` integer DEFAULT 0 NOT NULL,
	`phone_mobile` text,
	`phone_mobile_verified` integer DEFAULT 0 NOT NULL,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`country` text DEFAULT 'USA',
	`timezone` text DEFAULT 'America/New_York',
	`image_url` text,
	`image_thumb_url` text,
	`experience` integer,
	`specialties` text,
	`tools` text,
	`style` text,
	`description_short` text,
	`description_long` text,
	`rating` text,
	`premier` integer DEFAULT 0 NOT NULL,
	`rising_talent` integer DEFAULT 0 NOT NULL,
	`is_new` integer DEFAULT 1 NOT NULL,
	`method_chat` integer DEFAULT 0 NOT NULL,
	`method_text` integer DEFAULT 0 NOT NULL,
	`method_phone` integer DEFAULT 0 NOT NULL,
	`method_video` integer DEFAULT 0 NOT NULL,
	`rate_chat` integer,
	`rate_text` integer,
	`rate_phone` integer,
	`rate_video` integer,
	`rate_percentage` integer DEFAULT 7000 NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `advisors_clerk_user_id_unique` ON `advisors` (`clerk_user_id`);--> statement-breakpoint
CREATE TABLE `clients` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`available` integer DEFAULT 0 NOT NULL,
	`clerk_user_id` text,
	`name_first` text,
	`name_last` text,
	`email` text NOT NULL,
	`email_verified` integer DEFAULT 0 NOT NULL,
	`phone` text,
	`phone_verified` integer DEFAULT 0 NOT NULL,
	`phone_mobile` text,
	`phone_mobile_verified` integer DEFAULT 0 NOT NULL,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`country` text DEFAULT 'USA',
	`dob` text,
	`timezone` text DEFAULT 'America/New_York',
	`image_url` text,
	`image_thumb_url` text,
	`notification_feedback` integer DEFAULT 1 NOT NULL,
	`notification_offers` integer DEFAULT 1 NOT NULL,
	`notification_newsletter` integer DEFAULT 1 NOT NULL,
	`notification_referrals` integer DEFAULT 1 NOT NULL,
	`notification_surveys` integer DEFAULT 1 NOT NULL,
	`refill_status` integer DEFAULT 0 NOT NULL,
	`agreed_use_saved_cards` integer DEFAULT 0 NOT NULL,
	`backup_payments_status` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX `clients_clerk_user_id_unique` ON `clients` (`clerk_user_id`);--> statement-breakpoint
CREATE TABLE `advisor_availability` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`group_id` text,
	`advisor_id` integer NOT NULL,
	`day_of_week` integer NOT NULL,
	`start_time` text NOT NULL,
	`end_time` text NOT NULL,
	`status` text DEFAULT 'available' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `advisor_exclusions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`advisor_id` integer NOT NULL,
	`start_time` integer NOT NULL,
	`end_time` integer NOT NULL,
	`type` text DEFAULT 'time_off' NOT NULL,
	`reason` text,
	`created_at` integer NOT NULL,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `advisor_types` (
	`advisor_id` integer NOT NULL,
	`type_id` integer NOT NULL,
	PRIMARY KEY(`advisor_id`, `type_id`),
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`type_id`) REFERENCES `reading_types`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `favorites` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`client_id` integer NOT NULL,
	`advisor_id` integer NOT NULL,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `reading_types` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`description_short` text,
	`variable` text,
	`icon` text,
	`sort_order` integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE `chat_messages` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`reading_id` integer NOT NULL,
	`advisor_id` integer,
	`client_id` integer,
	`direction` integer NOT NULL,
	`message` text NOT NULL,
	`message_status` integer DEFAULT 1 NOT NULL,
	`reading_status` integer NOT NULL,
	`client_processed` integer DEFAULT 0 NOT NULL,
	`advisor_processed` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`reading_id`) REFERENCES `readings`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `reading_timers` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`reading_id` integer NOT NULL,
	`started_at` integer,
	`paused_at` integer,
	`elapsed_seconds` integer DEFAULT 0 NOT NULL,
	`budget_seconds` integer,
	`warning_sent_at` integer,
	FOREIGN KEY (`reading_id`) REFERENCES `readings`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `readings` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`started_at` integer,
	`ended_at` integer,
	`status` integer DEFAULT 2 NOT NULL,
	`advisor_id` integer NOT NULL,
	`client_id` integer NOT NULL,
	`client_name` text,
	`advisor_name` text,
	`method` integer NOT NULL,
	`client_joined` integer DEFAULT 0 NOT NULL,
	`advisor_joined` integer DEFAULT 0 NOT NULL,
	`end_session` integer DEFAULT 0 NOT NULL,
	`length` integer DEFAULT 0 NOT NULL,
	`response_time` text,
	`client_dob` text,
	`client_situation` text,
	`client_question` text,
	`client_answer` text,
	`advisor_answer` text,
	`transcript` text,
	`recording_id` text,
	`text_to_client` integer DEFAULT 0 NOT NULL,
	`text_to_client_sent` integer DEFAULT 0 NOT NULL,
	`email_to_client` integer DEFAULT 0 NOT NULL,
	`email_to_client_sent` integer DEFAULT 0 NOT NULL,
	`rate` integer NOT NULL,
	`revenue` integer DEFAULT 0 NOT NULL,
	`advisor_percentage` integer NOT NULL,
	`commission` integer DEFAULT 0 NOT NULL,
	`terms_accepted` integer DEFAULT 0 NOT NULL,
	`is_free` integer DEFAULT 0 NOT NULL,
	`budget_expires` integer,
	`budget_max` integer,
	`budget_action` text,
	`budget_warn_sent` integer DEFAULT 0 NOT NULL,
	`conference_sid` text,
	`first_joiner_call_sid` text,
	`messages_client` text,
	`messages_advisor` text,
	`notes` text,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `balances` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`client_id` integer,
	`advisor_id` integer,
	`admin_id` integer,
	`balance_cash` integer DEFAULT 0 NOT NULL,
	`balance_bonus` integer DEFAULT 0 NOT NULL,
	`balance_total` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`admin_id`) REFERENCES `admins`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `payment_methods` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`client_id` integer NOT NULL,
	`first_name` text,
	`last_name` text,
	`company` text,
	`address` text,
	`city` text,
	`state` text,
	`zip` text,
	`country` text DEFAULT 'USA',
	`last_four` text NOT NULL,
	`expiration_date` text,
	`card_type` integer DEFAULT 0 NOT NULL,
	`customer_profile_id` text,
	`payment_profile_id` text,
	`shipping_profile_id` text,
	`is_default` integer DEFAULT 0 NOT NULL,
	`agreed_saved` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `payments` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`client_id` integer NOT NULL,
	`payment_method_id` integer,
	`amount` integer NOT NULL,
	`transaction_id` text,
	`response_code` text,
	`message_code` text,
	`auth_code` text,
	`ref_id` text,
	`invoice_number` text,
	`description` text,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `wallet_transactions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`status` integer DEFAULT 1 NOT NULL,
	`type` text NOT NULL,
	`account_type` integer NOT NULL,
	`client_id` integer,
	`advisor_id` integer,
	`admin_id` integer,
	`reading_id` integer,
	`payment_id` integer,
	`payment_method_id` integer,
	`reading_method` integer,
	`amount_cash` integer DEFAULT 0 NOT NULL,
	`amount_bonus` integer DEFAULT 0 NOT NULL,
	`amount_total` integer DEFAULT 0 NOT NULL,
	`balance_cash` integer DEFAULT 0 NOT NULL,
	`balance_bonus` integer DEFAULT 0 NOT NULL,
	`balance_total` integer DEFAULT 0 NOT NULL,
	`payment_method` text,
	`credit_card_last4` text,
	`credit_card_name` text,
	`vendor_transaction_id` text,
	`vendor_refund_id` text,
	`description` text,
	`client_name` text,
	`advisor_name` text,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`admin_id`) REFERENCES `admins`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`reading_id`) REFERENCES `readings`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`payment_id`) REFERENCES `payments`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`payment_method_id`) REFERENCES `payment_methods`(`id`) ON UPDATE no action ON DELETE no action
);
--> statement-breakpoint
CREATE TABLE `reviews` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	`status` integer DEFAULT 0 NOT NULL,
	`reading_id` integer,
	`advisor_id` integer NOT NULL,
	`client_id` integer NOT NULL,
	`reviewer_name` text,
	`advisor_name` text,
	`rating` integer NOT NULL,
	`description` text,
	`thumbs_up` integer DEFAULT 0 NOT NULL,
	`thumbs_down` integer DEFAULT 0 NOT NULL,
	`sort_order` integer DEFAULT 0 NOT NULL,
	`featured` integer DEFAULT 0 NOT NULL,
	`reply_status` integer DEFAULT 0 NOT NULL,
	`reply_text` text,
	`replied_at` integer,
	FOREIGN KEY (`reading_id`) REFERENCES `readings`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`advisor_id`) REFERENCES `advisors`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`client_id`) REFERENCES `clients`(`id`) ON UPDATE no action ON DELETE no action
);
